name: Angular Deploy


on: 
  push: # Verify ever push and after that all branches
    branches: ["*"] # All branches needs be recoginezed.

jobs: 
  build: # Choose the machine like: Ubuntu
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - name: install
      - run: npm ci

      - name: lint
      - run: npm run lint

      - name: build
      - run: npm run build


